apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-moments-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Moments Management"
    rbac.authorization.halo.run/display-name: "瞬间查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:moments:view"]
rules:
  - apiGroups: [ "moment.halo.run"]
    resources: [ "moments" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.plugin.halo.run"]
    resources: [ "plugins/moments" ]
    resourceNames: [ "PluginMoments" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-moments-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Moments Management"
    rbac.authorization.halo.run/display-name: "瞬间管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:moments:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-moments-view"]
rules:
  - apiGroups: [ "moment.halo.run"]
    resources: [ "moments" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
  - apiGroups: [ "api.plugin.halo.run"]
    resources: [ "plugins/moments" ]
    resourceNames: [ "PluginMoments" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
