apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-moments-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: 瞬间列表显示条数
          name: pageSize
          validation: required|Number
          value: 10